### ISSUE TITLE
Module issues

### ISSUE THREAD

**Issue by shirishp** [aquasecurity/tfsec-pr-commenter-action#12]
Started getting following issue in the builds today:

```
go: downloading github.com/tfsec/tfsec v0.45.8
go get: github.com/tfsec/tfsec@v0.45.4 updating to
	github.com/tfsec/tfsec@v0.45.8: parsing go.mod:
	module declares its path as: github.com/aquasecurity/tfsec
	        but was required as: github.com/tfsec/tfsec
/entrypoint.sh: line 34: /go/bin/tfsec: No such file or directory
```

I feel the commit which is causing this is https://github.com/aquasecurity/tfsec-pr-commenter-action/commit/dea8bac3491955ba2908e98cb4429747359893e6

----

As a side note, I see that we now have releases https://github.com/aquasecurity/tfsec-pr-commenter-action/releases
Would it be better to update the README to use something like 
```
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v0.1.7
        with:
          github_token: ${{ github.token }}
```
instead of 
```
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ github.token }}
```
