### ISSUE TITLE
tfsec fails with `strconv.Atoi: parsing "<nil>": invalid syntax` error

### ISSUE THREAD

**Issue by giorgiocerruti** [aquasecurity/tfsec-pr-commenter-action#16]
Hi, 
I still getting this error on my pipeline

```
The commenter failed with the following error:
strconv.Atoi: parsing "<nil>": invalid syntax
```

this is my workflow

```
name: Terraform CI
on:
  issue_comment:
    types:
      - created
    branches:
      - master
jobs:
  tfsec:
   name: Terraform tests
   if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test') }}
   runs-on: ubuntu-20.04
   steps:
     - name: Checkout the project
       uses: actions/checkout@v2
     - name: Debug
       run: ls -al
     - name: Run tfsec
       uses: aquasecurity/tfsec-pr-commenter-action@main
       if: always()
       with:
        github_token: ${{ github.token }}
        working_directory: ./innovation1
```

What am I doing wrong here?

Thank you.
