### ISSUE TITLE
The commenter fails with the error "invalid character '/' looking for beginning of value"

### ISSUE THREAD

**Issue by suomit-pki** [aquasecurity/tfsec-pr-commenter-action#17]
Hi,

I'm running the latest @main version of the action. When I run it, it fails and in the logs it says:

`
Starting the github commenter...
The commenter failed with the following error:
invalid character '/' looking for beginning of value
`

Looking at the cmd/commenter/commenter.go code and the error message, it seems to come from the JSON-library, so maybe parsing the event.json file or the results.json file fails?

**Comment by owenrumney** [comment]
Hey @suomit-pki  - sorry for the delay in getting to this. Is it still an issue? I think I've seen this when bad output landsin in the results.json so might be worth running again from @main

again, apologies for the delay

**Comment by abagayev** [comment]
@jgrumboe can you please share your workflow?

**Comment by jgrumboe** [comment]
Sure.

```
name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v0.1.10
        with:
          github_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
```

**Comment by abagayev** [comment]
Thanks for sharing! 

So I've investigated my problem and problem was in tfsec code validating. With invalid code style tfsec breaks:
```
$ tfsec 
tags.tf:50,31-36: Missing attribute separator; Expected a newline or comma to mark the beginning of the next attribute.
```

And breaks not on JSON format. That's why commenting isn't working.

**Comment by jgrumboe** [comment]
Good point! I had only successful code and not tested a tfsec hit ... need to do that.

**Comment by erzz** [comment]
I get the same with invalid character 'T'

```
+ TFSEC_VERSION=latest
+ '[' latest '!=' latest ']'
++ wget -q https://api.github.com/repos/aquasecurity/tfsec/releases/latest -O -
++ grep -o -E 'https://.+?tfsec-linux-amd64'
++ head -n1
+ wget -O - -q https://github.com/aquasecurity/tfsec/releases/download/v0.63.1/tfsec-linux-amd64
+ install tfsec /usr/local/bin/
+ COMMENTER_VERSION=latest
+ '[' latest '!=' latest ']'
++ wget -q https://api.github.com/repos/aquasecurity/tfsec-pr-commenter-action/releases/latest -O -
++ grep -o -E 'https://.+?commenter-linux-amd64'
+ wget -O - -q https://github.com/aquasecurity/tfsec-pr-commenter-action/releases/download/v0.1.10/commenter-linux-amd64
+ install commenter /usr/local/bin/
+ '[' -n /github/workspace ']'
+ cd /github/workspace
+ tfsec --format=json terraform
+ echo 'tfsec violations were identified, running commenter...'
tfsec violations were identified, running commenter...
+ commenter
Starting the github commenter...
The commenter failed with the following error:
failed to load results. invalid character 'T' looking for beginning of value
```

Job:

```yaml
tfsec:
    name: tfsec Scan
    runs-on: ubuntu-latest
    steps:
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v0.1.10
        with:
          github_token: ${{ secrets.token }}
          working_directory: ${{ inputs.path }}
          tfsec_version: ${{ inputs.tfsec-version }}
          commenter_version: latest
```

Resolved values of the inputs there are:

```
working_directory: terraform
tfsec_version: latest
```
