### ISSUE TITLE
Potentially Incorrect release - broken action

### ISSUE THREAD

**Issue by shirishp** [aquasecurity/tfsec-pr-commenter-action#25]
Started getting following error in builds today.
```
Build container for action use: '/home/runner/work/_actions/aquasecurity/tfsec-pr-commenter-action/v0.1.7/Dockerfile'.
  /usr/bin/docker build -t 48c179:0de79bb338664d1bb08987acd8692b1c -f "/home/runner/work/_actions/aquasecurity/tfsec-pr-commenter-action/v0.1.7/Dockerfile" "/home/runner/work/_actions/aquasecurity/tfsec-pr-commenter-action/v0.1.7"
  Sending build context to Docker daemon  2.293MB
  
  Step 1/6 : FROM alpine:3.12
   ---> 48b8ec4ed9eb
  Step 2/6 : RUN apk --no-cache --update add bash git     && rm -rf /var/cache/apk/*
   ---> Running in cb274213397d
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
  (1/10) Installing ncurses-terminfo-base (6.2_p20200523-r0)
  (2/10) Installing ncurses-libs (6.2_p20200523-r0)
  (3/10) Installing readline (8.0.4-r0)
  (4/10) Installing bash (5.0.17-r0)
  Executing bash-5.0.17-r0.post-install
  (5/10) Installing ca-certificates (20191127-r4)
  (6/10) Installing nghttp2-libs (1.41.0-r0)
  (7/10) Installing libcurl (7.79.1-r0)
  (8/10) Installing expat (2.2.9-r1)
  (9/10) Installing pcre2 (10.35-r0)
  (10/10) Installing git (2.26.3-r0)
  Executing busybox-1.31.1-r20.trigger
  Executing ca-certificates-20191127-r4.trigger
  OK: 24 MiB in 24 packages
  Removing intermediate container cb274213397d
   ---> 1598f05e932a
  Step 3/6 : RUN wget -O - -q "$(wget -q https://api.github.com/repos/tfsec/tfsec/releases/latest -O - | grep -o -E "https://.+?tfsec-linux-amd64" | head -n1)" > tfsec     && install tfsec /usr/local/bin/
   ---> Running in a482abbb67bc
  Removing intermediate container a482abbb67bc
   ---> 855eeed92f9a
  Step 4/6 : RUN wget -O - -q "$(wget -q https://api.github.com/repos/tfsec/tfsec-pr-commenter-action/releases/latest -O - | grep -o -E "https://.+?commenter-linux-amd64")" > commenter     && install commenter /usr/local/bin/
   ---> Running in 5ac790de8b6a
  wget: bad address ''
  The command '/bin/sh -c wget -O - -q "$(wget -q https://api.github.com/repos/tfsec/tfsec-pr-commenter-action/releases/latest -O - | grep -o -E "https://.+?commenter-linux-amd64")" > commenter     && install commenter /usr/local/bin/' returned a non-zero code: 1
```
Actions file
```yaml
name: tfsec

on:
  push:
    branches:
      - main
      
  pull_request:

jobs:
  tfsec:
    name: Terraform Security Scan and PR Commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Pull Request Commenter
        if: ${{ github.event_name == 'pull_request' }}
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.0
        with :
          tfsec_output_format: JSON
```

@owenrumney I tried checking https://api.github.com/repos/tfsec/tfsec-pr-commenter-action/releases/latest , but it does not have text `commenter-linux-amd64`. Can you please check what happened?
