### ISSUE TITLE
tfsec not finding low level severities in Github Actions  

### ISSUE THREAD

**Issue by jigar-komodo** [aquasecurity/tfsec-pr-commenter-action#36]
When I run `tfsec .` locally on my laptop, it seems to find the LOW severity but not when I run it in Github Actions using aquasecurity/tfsec-pr-commenter-action. All terraform files are in repo's base directory

Github workflow:
```
name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ github.token }}
```

Output in GA:
```
+ TFSEC_VERSION=latest
+ '[' latest '!=' latest ']'
++ grep -o -E 'https://.+?tfsec-linux-amd64'
++ wget -q https://api.github.com/repos/aquasecurity/tfsec/releases/latest -O -
++ head -n1
+ wget -O - -q https://github.com/aquasecurity/tfsec/releases/download/v0.63.1/tfsec-linux-amd64
+ install tfsec /usr/local/bin/
+ COMMENTER_VERSION=latest
+ '[' latest '!=' latest ']'
++ wget -q https://api.github.com/repos/aquasecurity/tfsec-pr-commenter-action/releases/latest -O -
++ grep -o -E 'https://.+?commenter-linux-amd64'
+ wget -O - -q https://github.com/aquasecurity/tfsec-pr-commenter-action/releases/download/v0.1.10/commenter-linux-amd64
+ install commenter /usr/local/bin/
+ '[' -n /github/workspace ']'
+ cd /github/workspace
+ tfsec --format=json .
```

Output when I run it locally:
```
{
	"results": [
		{
			"rule_id": "aws-vpc-add-description-to-security-group",
			"legacy_rule_id": "AWS018",
			"rule_description": "Missing description for security group/security group rule.",
			"rule_provider": "aws",
			"rule_service": "vpc",
			"impact": "Descriptions provide context for the firewall rule reasons",
			"resolution": "Add descriptions for all security groups and rules",
			"links": [
				"https://aquasecurity.github.io/tfsec/latest/checks/aws/vpc/add-description-to-security-group",
				"https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group",
				"https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule",
				"https://www.cloudconformity.com/knowledge-base/aws/EC2/security-group-rules-description.html"
			],
			"description": "Resource 'aws_security_group.additional_ec2_sg' has ingress without description.",
			"severity": "LOW",
			"status": "failed",
			"location": {
				"filename": "***/main.tf",
				"start_line": 18,
				"end_line": 36
			},
			"resource": "aws_security_group.additional_ec2_sg"
		}
	]
}
```
