### ISSUE TITLE
tfsec doesnt fail the test when it finds vulnerabilities or commenter is failing 

### ISSUE THREAD

**Issue by jigar-komodo** [aquasecurity/tfsec-pr-commenter-action#37]
After adding a public 0.0.0.0/0 ingress rule, GA doesnt seem to fail the Github Action job or add comments to the PR. It does find the vulnerability when I run `tfsec .` locally. 

Github Action: 
```
name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ github.token }}
``` 

Output:
```
+ TFSEC_VERSION=latest
+ '[' latest '!=' latest ']'
++ wget -q https://api.github.com/repos/aquasecurity/tfsec/releases/latest -O -
++ head -n1
++ grep -o -E 'https://.+?tfsec-linux-amd64'
+ wget -O - -q https://github.com/aquasecurity/tfsec/releases/download/v0.63.1/tfsec-linux-amd64
+ install tfsec /usr/local/bin/
+ COMMENTER_VERSION=latest
+ '[' latest '!=' latest ']'
++ wget -q https://api.github.com/repos/aquasecurity/tfsec-pr-commenter-action/releases/latest -O -
++ grep -o -E 'https://.+?commenter-linux-amd64'
+ wget -O - -q https://github.com/aquasecurity/tfsec-pr-commenter-action/releases/download/v0.1.10/commenter-linux-amd64
+ install commenter /usr/local/bin/
+ '[' -n /github/workspace ']'
+ cd /github/workspace
+ tfsec --format=json .
+ echo 'tfsec violations were identified, running commenter...'
+ commenter
tfsec violations were identified, running commenter...
Starting the github commenter...
There were 2 errors:
there were errors processing the PR files.
the patch details could not be resolved
there were errors processing the PR files.
the patch details could not be resolved
```
