### ISSUE TITLE
no such file or directory on symbolic link

### ISSUE THREAD

**Issue by vkannemacher** [aquasecurity/tfsec-pr-commenter-action#51]
Hi,
Having multiple environments deployed on AWS, we created symbolic links between the files defining common ressources needed in our environment and specific ones, which give the following files hierarchy:
```
├── common
│   └── common_ressource.tf
├── preprod
│   ├── dedicated_ressource.tf
│   └── common_ressource.tf -> ../common/common_ressource.tf
```
Running TFsec locally in my `preprod` folder doesn't raise any error but running the PR commenter action does:
```
+ TFSEC_VERSION=latest
+ '[' latest '!=' latest ']'
++ wget -q https://api.github.com/repos/aquasecurity/tfsec/releases/latest -O -
++ grep -o -E 'https://.+?tfsec-linux-amd64'
++ head -n1
+ wget -O - -q https://github.com/aquasecurity/tfsec/releases/download/v1.4.2/tfsec-linux-amd64
+ install tfsec /usr/local/bin/
+ COMMENTER_VERSION=latest
+ '[' latest '!=' latest ']'
++ grep -o -E 'https://.+?commenter-linux-amd64'
++ wget -q https://api.github.com/repos/aquasecurity/tfsec-pr-commenter-action/releases/latest -O -
+ wget -O - -q https://github.com/aquasecurity/tfsec-pr-commenter-action/releases/download/v1.0.5/commenter-linux-amd64
+ install commenter /usr/local/bin/
+ '[' -n /github/workspace ']'
+ cd /github/workspace
+ '[' -n '' ']'
+ tfsec --out=results.json --format=json --soft-fail terraform/preprod
WARNING: A tfvars file was found but not automatically used. Did you mean to specify the --tfvars-file flag?
Scan error: open /github/workspace/terraform/preprod/common_ressource.tf: no such file or directory
+ commenter
Starting the github commenter...
The commenter failed with the following error:
failed to load results. open results.json: no such file or directory
```

My github workflow is written as follows:
```
name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.0.2
        with:
          github_token: ${{ github.token }}
          working_directory: terraform/preprod
```
Note that setting `working_directory` on `terraform/common` works perfecly.
