### ISSUE TITLE
.... not writing as not part of the current PR

### ISSUE THREAD

**Issue by cvs79** [aquasecurity/tfsec-pr-commenter-action#54]
Integrated the commenter in my pipeline. It finds issues after some tweaking of the working directory. 

But now it doenst write them to the PR as a comment. It keeps saying that the issue found is not part of the PR. 

I've explicitly made an extea change to the file (keyvault.tf) in this case but that still results in the same logging output.

Any ideas?

**Comment by landradetractian** [comment]
I'm getting this same problem, implemented this snippet below inside `.github/workflows/tfsec_pr_commenter.yml`:

```
name: tfsec-pr-commenter

on:
  pull_request:

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}
```

I opened a PR and workflows runs fine, in `tfsec` step it finds some problems, but for all of them, `not writing as not part of the current PR`.

Is there some flag or option to enable comments about all repo files in every PR?

**Comment by smaeda-ks** [comment]
@owenrumney I think the issue is that when using the `working_directory` option, it fails to lookup the file:
https://github.com/aquasecurity/tfsec-pr-commenter-action/blob/v1.2.0/cmd/commenter/commenter.go#L51-L56

If I understand it correctly, when providing a path to tfsec CLI, the output filename would be a relative path from that path.
So it eventually hits this condition: https://github.com/aquasecurity/tfsec-pr-commenter-action/blob/1015a3975c7f1400ee4d9f423a7786a3df9fcbec/vendor/github.com/owenrumney/go-github-pr-commenter/commenter/commenter.go#L159
and that's where causing this issue, I guess.

**Comment by harmw** [comment]
having the same issue here, fresh PR with files that are supposedly _not good_ but are new as of this PR workflow:

```
1 file(s) written: results.json
Starting the github commenter...
Image scanning is not enabled. .... not writing as not part of the current PR
Repository tags are mutable. .... not writing as not part of the current PR
```

I've changed from using `working_directory: terraform` (my TF code is all in /terraform) to not having that key set at all - no difference.

Workflow:
```
      - name: Run TFsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          working_directory: terraform
          soft_fail_commenter: true
          tfsec_args: --soft-fail --concise-output --include-passed --minimum-severity MEDIUM
          github_token: ${{ github.token }}
```
