### ISSUE TITLE
Failed to upload configuration files .tfsec, permission denied when combining with remote terraform

### ISSUE THREAD

**Issue by bneijt** [aquasecurity/tfsec-pr-commenter-action#58]
This action downloads/creates files that the are not accessible outside of the action step.

When using a remote terraform backend, this leads to an error like
```
Error: Failed to upload configuration files: open /home/runner/work/orchestration/orchestration/infra/.tfsec: permission denied
```
with the latest version of tfsec which automatically downloads remote modules https://github.com/aquasecurity/tfsec/releases/tag/v1.15.0

My first attempt to fix this was using `.terraformignore` to ignore the `.tfsec` folder. However, it seems like terraform tries a recursive listing of files and directories _before_ applying the `.terraformignore`. And the .tfsec folder is not executable (listable) for the github action user after running this action.

Workaround is doing `terraform init` before the tfsec step and adding the `--no-module-downloads`:
```
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ github.token }}
          tfsec_args: --no-module-downloads
```

and making sure I do terraform init before I run this tfsec action.

It would be great if the tfsec action would use a user that allows the github action steps after the docker run to list and/or remove the created `.tfsec` directory.
